export enum ACCOUNT_TYPE{
    LOAD_ACCOUNT_START='LOAD_ACCOUNT_START',
    LOAD_ACCOUNT_SUCCESS = 'LOAD_ACCOUNT_SUCCESS',
    LOAD_ACCOUNT_FAIL = 'LOAD_ACCOUNT_FAIL'
}

export enum NETWORK_TYPE{
    LOAD_NETWORKID_START='LOAD_NETWORKID_START',
    LOAD_NETWORKID_SUCCESS = 'LOAD_NETWORKID_SUCCESS',
    LOAD_NETWORKID_FAIL = 'LOAD_NETWORKID_FAIL'
}

export enum CONTRACT_TYPE{
    LOAD_CONTRACT_START='LOAD_CONTRACT_START',
    LOAD_CONTRACT_SUCCESS = 'LOAD_CONTRACT_SUCCESS',
    LOAD_CONTRACT_FAIL = 'LOAD_CONTRACT_FAIL'
}
export enum ALERT_TYPE{
    ALERT_PROCESSING='ALERT_PROCESSING',
    ALERT_SUCCESS = 'ALERT_SUCCESS',
    ALERT_FAIL = 'ALERT_FAIL',
    ALERT_INIT ='ALERT_INIT'
}

export enum SUPPLY_TYPE{
    SUPPLY_START='SUPPLY_START',
    SUPPLY_SUCCESS = 'SUPPLY_SUCCESS',
    SUPPLY_FAIL = 'SUPPLY_FAIL'
}

export enum BORROW_TYPE{
    BORROW_START='BORROW_START',
    BORROW_SUCCESS = 'BORROW_SUCCESS',
    BORROW_FAIL = 'BORROW_FAIL'
}

export enum REPAY_TYPE{
    REPAY_START='REPAY_START',
    REPAY_SUCCESS = 'REPAY_SUCCESS',
    REPAY_FAIL = 'REPAY_FAIL'
}
export enum WITHDRAW_TYPE{
    WITHDRAW_START='WITHDRAW_START',
    WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS',
    WITHDRAW_FAIL = 'WITHDRAW_FAIL'
}

export enum SET_COLLATERAL_TYPE {
    SET_COLLATERAL_START='SET_COLLATERAL_START',
    SET_COLLATERAL_SUCCESS='SET_COLLATERAL_SUCCESS' ,
    SET_COLLATERAL_FAIL='SET_COLLATERAL_FAIL' 
}

export enum GET_POOLS_TYPE{
    GET_POOLS_DATA_LOAD_START='GET_POOLS_DATA_LOAD_START',
    GET_POOLS_DATA_LOAD_SUCCESS = 'GET_POOLS_DATA_LOAD_SUCCESS',
    GET_POOLS_DATA_LOAD_FAIL = 'GET_POOLS_DATA_LOAD_FAIL'
}

export enum GET_BALANCES_TYPE{
    GET_BALANCES_START='GET_BALANCES_START',
    GET_BALANCES_SUCCESS = 'GET_BALANCES_SUCCESS',
    GET_BALANCES_FAIL = 'GET_BALANCES_FAIL'
}